### ISSUE TITLE
Support Generating Key Vault Secrets from TSP

### ISSUE THREAD

**Issue by RickWinter** [Azure/typespec-rust#53]
Generate KeyVault Secrets from TSP.

Secrets: [[Key Vault] TypeSpec for Secrets library by mccoyp (#29249)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs%2Fpull%2F29249&data=05%7C02%7CRick.Winter%40microsoft.com%7C62e135c9a774455a829208dcaccf2029%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638575252805698129%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=nX6xXgGwxu5inSVixq8KFDjpAQPydL7OPoMdK8Ylxbk%3D&reserved=0)

```[tasklist]
### Support required for Key Vault that is done (feature needs more to closed)
- [ ] https://github.com/Azure/autorest.rust/issues/55
- [ ] https://github.com/Azure/autorest.rust/issues/56
- [ ] https://github.com/Azure/autorest.rust/issues/58
- [ ] https://github.com/Azure/autorest.rust/issues/59
- [ ] https://github.com/Azure/autorest.rust/issues/54
```
